name: PHP Images

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  LATEST_VERSION: 8.4
  IMAGE_NAME: awesoft/php
  IMAGE_TITLE: Awesoft PHP Image
  IMAGE_DESCRIPTION: A minimal, production-ready PHP Docker image built on Alpine Linux

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4

    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_VERSION=${{ matrix.php }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.php }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.php }}-${{ github.run_id }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-${{ matrix.php }}
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-${{ matrix.php }},mode=max
          annotations: |
            org.opencontainers.image.title=${{ env.IMAGE_TITLE }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.authors=https://github.com/awesoft
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.version=${{ matrix.php }}
            org.opencontainers.image.revision=${{ github.run_id }}
            org.opencontainers.image.base.name=php:${{ matrix.php }}-fpm-alpine
            org.opencontainers.image.vendor=Awesoft
            org.opencontainers.image.ref.name=PHP v${{ matrix.php }}

      - name: Tag as latest image
        if: matrix.php == env.LATEST_VERSION
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_VERSION=${{ env.LATEST_VERSION }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-${{ env.LATEST_VERSION }}
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-${{ env.LATEST_VERSION }},mode=max
          annotations: |
            org.opencontainers.image.title=${{ env.IMAGE_TITLE }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.authors=https://github.com/awesoft
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.version=latest
            org.opencontainers.image.revision=${{ github.run_id }}
            org.opencontainers.image.base.name=php:${{ env.LATEST_VERSION }}-fpm-alpine
            org.opencontainers.image.vendor=Awesoft
            org.opencontainers.image.ref.name=PHP v${{ env.LATEST_VERSION }}
